name: workflow-prueba
on:
  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container: node:14.16.0-slim

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Checkout python
        uses: actions/setup-python@v2
        with:
          python-version: "python-3.9.6-linux-16.04-x64.tar.gz"
          architecture: "x64"

      - name: Install OpenSSL
        run: apt-get -qy update && apt-get -qy install openssl

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: python3 -m unittes
